let products = [
  { image: "https://atharv1507.github.io/BankimWeb/photos/ring.jpeg", category: "ring", name: "The Reflection", price: 2000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/ring2.jpeg", category: "ring", name: "Boho Classic", price: 2500 },

  { image: "https://atharv1507.github.io/BankimWeb/photos/boho.jpeg", category: "boho", name: "Boho Elegance", price: 3500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/boho2.jpeg", category: "boho", name: "Boho Charm", price: 5500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/boho3.jpeg", category: "boho", name: "Boho Serenity", price: 5000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/boho4.jpeg", category: "boho", name: "Boho Dream", price: 4800 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/boho5.jpeg", category: "boho", name: "Boho Spirit", price: 3500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/boho6.jpeg", category: "boho", name: "Boho Vision", price: 4800 },
  //new category kids
  // { image: "https://atharv1507.github.io/BankimWeb/photos/kids.jpeg", category: "boho", name: "Boho Kids", price: 5500 },
  
  { image: "https://atharv1507.github.io/BankimWeb/photos/EVILEYE1.jpeg", category: "evileye", name: "The protector", price: 4500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/EVILEYE2.jpeg", category: "evileye", name: "The guardian", price: 5500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/EVILEYE3.jpeg", category: "evileye", name: "The Empress", price: 5000 },
  
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion2.jpeg", category: "modern-fusion", name: "Fusion Flow", price: 4800 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion3.jpeg", category: "modern-fusion", name: "Fusion Balance", price: 4000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion4.jpeg", category: "modern-fusion", name: "Fusion Pulse", price: 5000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion5.jpeg", category: "modern-fusion", name: "Fusion Harmony", price: 5000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion6.jpeg", category: "modern-fusion", name: "Fusion Rhythm", price: 4500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion7.jpeg", category: "modern-fusion", name: "Fusion Vibe", price: 4800 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion8.jpeg", category: "modern-fusion", name: "Fusion Spark", price: 3500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion9.jpeg", category: "modern-fusion", name: "Fusion Edge", price: 5000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion10.jpeg", category: "modern-fusion", name: "Fusion Vision", price: 4500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion12.jpeg", category: "modern-fusion", name: "Fusion Echo", price: 4000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion13.jpeg", category: "modern-fusion", name: "Fusion Nova", price: 4000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion14.jpeg", category: "modern-fusion", name: "Modern Breeze", price: 4500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion15.jpeg", category: "modern-fusion", name: "Modern Essence", price: 4800 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion16.jpeg", category: "modern-fusion", name: "Modern Spirit", price: 4000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion17.jpeg", category: "modern-fusion", name: "Modern Aura", price: 4500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion18.jpeg", category: "modern-fusion", name: "Modern Glow", price: 4800 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion19.jpeg", category: "modern-fusion", name: "Modern Shine", price: 4500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/modern-fusion20.jpeg", category: "modern-fusion", name: "Modern Radiance", price: 5000 },

  { image: "https://atharv1507.github.io/BankimWeb/photos/pichwai.jpeg", category: "pichwai", name: "Pichwai Heritage", price: 5000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/pichwai2.jpeg", category: "pichwai", name: "Pichwai Splendor", price: 5500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/pichwai3.jpeg", category: "pichwai", name: "Pichwai Grace", price: 5500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/pichwai4.jpeg", category: "pichwai", name: "Pichwai Lotus", price: 6000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/pichwai5.jpeg", category: "pichwai", name: "Pichwai Blossom", price: 5000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/pichwai6.jpeg", category: "pichwai", name: "Pichwai Divine", price: 5000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/pichwai7.jpeg", category: "pichwai", name: "Pichwai Classic", price: 5000 },

  { image: "https://atharv1507.github.io/BankimWeb/photos/sakhi2.jpeg", category: "sakhi", name: "Sakhi Reflection", price: 6000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/sakhi3.jpeg", category: "sakhi", name: "Sanjh", price: 6000},
  { image: "https://atharv1507.github.io/BankimWeb/photos/sakhi4.jpeg", category: "sakhi", name: "Sakhi Harmony", price: 6000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/sakhi.jpeg", category: "sakhi", name: "Rang Rani", price: 6000 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/sakhi5.jpeg", category: "sakhi", name: "Sakhi Grace", price: 5500 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/sakhi6.jpeg", category: "sakhi", name: "Royal Sakhi", price: 5800 },

  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi1.jpeg", category: "rakhi", name: "Rakhi Delight", price: 900 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi2.jpeg", category: "rakhi", name: "Rakhi Blessing", price: 900 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi3.jpeg", category: "rakhi", name: "Rakhi Love", price: 900 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi4.jpeg", category: "rakhi", name: "Rakhi Bond", price: 900 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi5.jpeg", category: "rakhi", name: "Rakhi Tradition", price: 900 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi6.jpeg", category: "rakhi", name: "Rakhi Joy", price: 900 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi7.jpeg", category: "rakhi", name: "Rakhi Charm", price: 900 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi8.jpeg", category: "rakhi", name: "Rakhi Elegance", price: 900 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi9.jpeg", category: "rakhi", name: "Rakhi Spirit", price: 900 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi10.jpeg", category: "rakhi", name: "Rakhi Heritage", price: 900 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi11.jpeg", category: "rakhi", name: "Rakhi Blessings", price: 900 },
  { image: "https://atharv1507.github.io/BankimWeb/photos/rakhi12.jpeg", category: "rakhi", name: "Rakhi Tradition", price: 900 },

];
