let products = [
  { image: "https://bankim.online/photos/ring.jpeg", category: "ring", name: "The Reflection", price: 2000 },
  { image: "https://bankim.online/photos/ring2.jpeg", category: "ring", name: "Boho Classic", price: 2500 },
  { image: "https://bankim.online/photos/ring3.jpeg", category: "ring", name: "Boho Teddy", price: 2000 },
  { image: "https://bankim.online/photos/ring4.jpeg", category: "ring", name: "Organic Orange", price: 2000 },
  { image: "https://bankim.online/photos/ring5.jpeg", category: "ring", name: "Turqoise Classic", price: 2000 },

  { image: "https://bankim.online/photos/boho.jpeg", category: "boho", name: "Boho Elegance", price: 3500 },
  { image: "https://bankim.online/photos/boho2.jpeg", category: "boho", name: "Boho Charm", price: 5500 },
  { image: "https://bankim.online/photos/boho3.jpeg", category: "boho", name: "Boho Serenity", price: 5000 },
  { image: "https://bankim.online/photos/boho4.jpeg", category: "boho", name: "Boho Dream", price: 4800 },
  { image: "https://bankim.online/photos/boho5.jpeg", category: "boho", name: "Boho Spirit", price: 3500 },
  { image: "https://bankim.online/photos/boho6.jpeg", category: "boho", name: "Boho Vision", price: 4800 },
  { image: "https://bankim.online/photos/boho7.jpeg", category: "boho", name: "Boho Vision", price: 5500 },
  { image: "https://bankim.online/photos/boho8.jpeg", category: "boho", name: "Boho Vintage", price: 5500 },
  //new category kids
  { image: "https://bankim.online/photos/kids.jpeg", category: "kids", name: "Jolly Boy", price: 3000 },
  { image: "https://bankim.online/photos/kids2.jpeg", category: "kids", name: "Unicorn World", price: 2500 },
  
  { image: "https://bankim.online/photos/EVILEYE1.jpeg", category: "evileye", name: "The protector", price: 4500 },
  { image: "https://bankim.online/photos/EVILEYE2.jpeg", category: "evileye", name: "The guardian", price: 5500 },
  { image: "https://bankim.online/photos/EVILEYE3.jpeg", category: "evileye", name: "The Empress", price: 5000 },
  
  { image: "https://bankim.online/photos/modern-fusion2.jpeg", category: "modern-fusion", name: "Fusion Flow", price: 4800 },
  { image: "https://bankim.online/photos/modern-fusion3.jpeg", category: "modern-fusion", name: "Fusion Balance", price: 4000 },
  { image: "https://bankim.online/photos/modern-fusion4.jpeg", category: "modern-fusion", name: "Fusion Pulse", price: 5000 },
  { image: "https://bankim.online/photos/modern-fusion5.jpeg", category: "modern-fusion", name: "Fusion Harmony", price: 5000 },
  { image: "https://bankim.online/photos/modern-fusion6.jpeg", category: "modern-fusion", name: "Fusion Rhythm", price: 4500 },
  { image: "https://bankim.online/photos/modern-fusion7.jpeg", category: "modern-fusion", name: "Fusion Vibe", price: 4800 },
  { image: "https://bankim.online/photos/modern-fusion8.jpeg", category: "modern-fusion", name: "Fusion Spark", price: 3500 },
  { image: "https://bankim.online/photos/modern-fusion9.jpeg", category: "modern-fusion", name: "Fusion Edge", price: 5000 },
  { image: "https://bankim.online/photos/modern-fusion10.jpeg", category: "modern-fusion", name: "Fusion Vision", price: 4500 },
  { image: "https://bankim.online/photos/modern-fusion12.jpeg", category: "modern-fusion", name: "Fusion Echo", price: 4000 },
  { image: "https://bankim.online/photos/modern-fusion13.jpeg", category: "modern-fusion", name: "Fusion Nova", price: 4000 },
  { image: "https://bankim.online/photos/modern-fusion14.jpeg", category: "modern-fusion", name: "Modern Breeze", price: 4500 },
  { image: "https://bankim.online/photos/modern-fusion15.jpeg", category: "modern-fusion", name: "Modern Essence", price: 4800 },
  { image: "https://bankim.online/photos/modern-fusion16.jpeg", category: "modern-fusion", name: "Modern Spirit", price: 4000 },
  { image: "https://bankim.online/photos/modern-fusion17.jpeg", category: "modern-fusion", name: "Modern Aura", price: 4500 },
  { image: "https://bankim.online/photos/modern-fusion18.jpeg", category: "modern-fusion", name: "Modern Glow", price: 4800 },
  { image: "https://bankim.online/photos/modern-fusion19.jpeg", category: "modern-fusion", name: "Modern Shine", price: 4500 },
  { image: "https://bankim.online/photos/modern-fusion20.jpeg", category: "modern-fusion", name: "Modern Radiance", price: 5000 },

  { image: "https://bankim.online/photos/pichwai.jpeg", category: "pichwai", name: "Pichwai Heritage", price: 5000 },
  { image: "https://bankim.online/photos/pichwai2.jpeg", category: "pichwai", name: "Pichwai Splendor", price: 5500 },
  { image: "https://bankim.online/photos/pichwai3.jpeg", category: "pichwai", name: "Pichwai Grace", price: 5500 },
  { image: "https://bankim.online/photos/pichwai4.jpeg", category: "pichwai", name: "Pichwai Lotus", price: 6000 },
  { image: "https://bankim.online/photos/pichwai5.jpeg", category: "pichwai", name: "Pichwai Blossom", price: 5000 },
  { image: "https://bankim.online/photos/pichwai6.jpeg", category: "pichwai", name: "Pichwai Divine", price: 5000 },
  { image: "https://bankim.online/photos/pichwai7.jpeg", category: "pichwai", name: "Pichwai Classic", price: 5000 },

  { image: "https://bankim.online/photos/sakhi2.jpeg", category: "sakhi", name: "Sakhi Reflection", price: 6000 },
  { image: "https://bankim.online/photos/sakhi3.jpeg", category: "sakhi", name: "Sanjh", price: 6000},
  { image: "https://bankim.online/photos/sakhi4.jpeg", category: "sakhi", name: "Sakhi Harmony", price: 6500 },
  { image: "https://bankim.online/photos/sakhi.jpeg", category: "sakhi", name: "Rang Rani", price: 6000 },
  { image: "https://bankim.online/photos/sakhi5.jpeg", category: "sakhi", name: "Sakhi Grace", price: 5500 },
  { image: "https://bankim.online/photos/sakhi6.jpeg", category: "sakhi", name: "Royal Sakhi", price: 5800 },

];
